name: post_tip
description: "A Flutter ToolTip widget"
version: 0.0.1
homepage: https://github.com/monolith-rnd/post-tip

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
